# frozen_string_literal: true

# Generated by kettle-jem-appraisals
# Do not edit directly — re-run `kettle-jem-appraisals --resolve` to regenerate.

appraise "kja-ar-5-2-r2.4" do
  eval_gemfile "modular/activerecord/r2.4/v5.2.gemfile"
  eval_gemfile "modular/x_std_libs/r2.4/libs.gemfile"
end

appraise "kja-ar-6-0-r2.6" do
  eval_gemfile "modular/activerecord/r2.6/v6.0.gemfile"
  eval_gemfile "modular/x_std_libs/r2.6/libs.gemfile"
end

appraise "kja-ar-6-1-r2.6" do
  eval_gemfile "modular/activerecord/r2.6/v6.1.gemfile"
  eval_gemfile "modular/x_std_libs/r2.6/libs.gemfile"
end

appraise "kja-ar-7-0-r2" do
  eval_gemfile "modular/activerecord/r2/v7.0.gemfile"
  eval_gemfile "modular/x_std_libs/r2/libs.gemfile"
end

appraise "kja-ar-7-1-r2" do
  eval_gemfile "modular/activerecord/r2/v7.1.gemfile"
  eval_gemfile "modular/x_std_libs/r2/libs.gemfile"
end

appraise "kja-ar-7-2-r3.1" do
  eval_gemfile "modular/activerecord/r3.1/v7.2.gemfile"
  eval_gemfile "modular/x_std_libs/r3.1/libs.gemfile"
end

appraise "kja-ar-8-0-r3" do
  eval_gemfile "modular/activerecord/r3/v8.0.gemfile"
  eval_gemfile "modular/x_std_libs/r3/libs.gemfile"
end
